stages:
  featurize:
    cmd: python scripts\featurization.py data\acidenteambiental.csv data\features
    deps:
    - data/acidenteambiental.csv
    - scripts/featurization.py
    params:
    - featurize.seed
    - featurize.split_test
    - featurize.split_val
    outs:
    - data\features
  train:
    cmd: python scripts\train.py data\features models
    deps:
    - data\features
    - scripts\train.py
    params:
    - train.bs
    - train.cv
    - train.epochs
    - train.lr
    outs:
    - models\model.pkl
  evaluate:
    cmd: python scripts\evaluate.py data\features models
    deps:
    - data\features
    - models\model.pkl
    - scripts\evaluate.py
    plots:
    - eval\live\plots\sklearn\roc:
        template: simple
        x: fpr
        y: tpr
        title: Receiver operating characteristic (ROC)
        x_label: False Positive Rate
        y_label: True Positive Rate
    - eval\live\plots\sklearn\cm:
        template: confusion
        x: actual
        y: predicted
        title: Confusion Matrix
        x_label: True Label
        y_label: Predicted Label
    metrics:
    - eval\live\metrics.json:
        cache: false
