stages:
  featurize:
    cmd: python scripts\featurization.py data\acidenteambiental.csv data\features
    deps:
    - data/acidenteambiental.csv
    - scripts/featurization.py
    params:
    - featurize.seed
    - featurize.split_test
    - featurize.split_val
    outs:
    - data\features
  train_tree:
    cmd: python scripts\train_tree.py data\features models
    deps:
    - data\features
    - scripts\train_tree.py
    params:
    - train_tree.cv
    outs:
    - models\clf_tree.pkl
  train_svm:
    cmd: python scripts\train_svm.py data\features models
    deps:
    - data\features
    - scripts\train_svm.py
    params:
    - train_svm.C
    - train_svm.gamma
    outs:
    - models\clf_svm.pkl
  train_nn:
    cmd: python scripts\train_nn.py data\features models
    deps:
    - data\features
    - scripts\train_nn.py
    params:
    - train_nn.lr
    - train_nn.epochs
    - train_nn.bs
    outs:
    - models\clf_nn.pkl
